name = "moving"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".vercel/output/static"

[env.production]
workers_dev = false

[workers]
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]